---
title: "Introduction"
bibliography: config/library.bib
csl: config/abnt-ufrgs-initials.csl
output: 
  word_document:
    reference_docx: config/template.docx
    keep_md: true
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
       fig.path = "Development_files/figure-docx/")
```

  Idiopathic Pulmonary Fibrosis (IPF) is a chronic, progressive, irreversible lung disease. After diagnosis, the interstitial condition commonly presents 3-5 years of life expectancy if untreated [@Wolters2018]. Alveolar damage is characterized by dilatation of the bronchi, tissue remodeling and parenchymal fibrosis which seriously impair gas exchange. The first time the current name was used it referred to radiography tests suggestive of pulmonary fibrosis of unknown etiology, although the disease had been recognized over one hundred years before - named cirrhosis of the lung at the time [@Robbins1948, @Wolters2018]. Over three decades after the nomenclature was first published, in 1976 it gained widespread use after a review article [@Wolters2018].
  
  Currently, radiographic and histopathological patterns of usual interstitial pneumonia (UIP) with apparently no secondary causes form the basis for IPF definition [@Richeldi2017]. The disease presents sporadic and familial forms. From the edges of the lungs - base and periphery -, spreads all over the pulmonary tissue causing dry cough, fatigue and dyspnea. The latter is nearly universal in the history of IPF patients and may progress over a period of years, while the first two may be absent in the early stages. Universal findings also include low diffusion capacity of the lung for carbon monoxide (DLCO) and Bilateral Velcro-like crackles. The chest radiograph may present nonspecific changes or bilateral basal reticular abnormalities [@Lederer2018]. The difficulty of the diagnosis is illustrated by the fact that clinicians often mistake the presence of dyspnea as indicator of heart failure or chronic obstructive pulmonary disease (COPD), failing to consider interstitial lung disease, which delays IPF detection significantly.
  
  Although its cause is not clear, there is currently a recognized increase in IPF prevalence worldwide [@Wolters2018]. As a disease of aging, this may be due to population increasing phenomena, but also to recent improvements in disease recognition [@Lederer2018]. Unusual before the 50 years of age, IPF prevalence almost doubles for every decade of life thereafter [@Wolters2018]. In North America and Europe, the incidence of IPF ranges from 3 to 9 cases per 100000 person-years, while South America and East Asia show less than 4 cases per 100000 person-years [@Hutchinson2015]. Assuming these numbers as conservative, a recent Brazilian study tried to calculate more precise estimates for the local reality. Using data from the 2010 Brazilian National Census and rates reported by previous studies, the authors suggested annual incidence of IPF between 6.841 and 9.997 cases per 100000 people, whereas the prevalence was estimated at a range of 13.9-18.3 cases per 100000 people [@Baddini-Martinez2015]. In terms of mortality, another study estimated 1.2 deaths per 100000 people in 2010, although this is certainly an underestimation as the authors limited their analysis to data from the Information Technology Department of the Brazilian Unified Health Care System (DATASUS), which does not reflect private medicine practices [@Rufino2013]. It is clear, however, that Brazil's data does not oppose the world tendency of IPF prevalence increase.
  
  The number of disease cases has risen along with the number of identified risk factors. In fact, when it comes to hospitalization, over three quarters of the cases are due to respiratory events, with acute exacerbations as the main cause [@Brown2015; @Song2011]. In-hospital mortality rate has been reported to reach 50 %, with five-year survival from initial diagnosis lower than 20 % [@Song2011]. In such a complex scenario, multidimensional indexes that include sex, age and physiological abnormalities may be useful to predict mortality [@Richeldi2017]. Risk factors also include environmental exposures to dust and air pollution, smoking, chronic viral infections ( _e.g._ Epstein–Barr virus, cytomegalovirus and Kaposi sarcoma-associated herpesvirus) and other comorbidities. Of note, one third of inherent individual risk of IPF have been attributed to genetic variants. Mutations in genes associated with telomere length - such as TERT, TERC, PARN, and RTEL1 - are related to higher higher risk of IPF. The same holds true for genes responsible for cell adhesion, integrity, and mechanotransduction ( _e.g._ DSP, AKAP13, CTNNA, and DPP9) [@Lederer2018].
  
  Mucin 5B overexpression in small-airway epithelial cells is a universal finding in patients with IPF, which has led to the hypothesis that impaired mucociliary clearance may be linked to changes in microbiome and innate immune responses that promote IPF [@Molyneaux2017; @Lederer2018]. Although the gene expression pattern appears to be genotype-independent, single-nucleotide polymorphisms in the MUC5B gene are notable risk factors for IPF, even though - paradoxically - they may also predict slower disease progression [@Peljto2015]. Host-microbiome interactions are also highlighted by the central role of macrophages in lung fibrosis development along with the finding that IPF risk is also increased by mutations in the TOLLIP gene, which encodes a protein associated with toll-like receptor family pathways [@Lederer2018]. Lung of patients typically present higher bacterial loads, differences in microbiota composition and diversity, and even increases in potentially pathogenic bacteria ( _e.g._ _Staphylococcus_ spp. and _Streptococcus_ spp.). Finally, epigenetic reprogramming has been associated with pathogeny of IPF [@Richeldi2017].  Upregulation of lung development genes, trans-regulatory methylation marks near transcription factors, and potentially pathogenic modifications in miRNAs have been pointed as complex reprogramming processes often associated with pro-fibrotic pathways. 
  
  Overall, it is well accepted that IPF arises from recurrent, subclinical epithelial injury, especially in genetically-predisposed individuals with accelerated epithelial aging [@Lederer2018].
  